using carequeue.CQ.API.Models.Entities;
using carequeue.CQ.API.Models.Enums;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace carequeue.CQ.API.Models.Entites
{
    [Table("Payments")]
    public class Payment
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PaymentId { get; set; }

        [Required]
        public int HospitalId { get; set; }

        [ForeignKey(nameof(HospitalId))]
        public Hospital Hospital { get; set; } = null!;

        [Required]
        public int CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        public Customer Customer { get; set; } = null!;

        [Required]
        public int AppointmentId { get; set; }

        [ForeignKey(nameof(AppointmentId))]
        public Appointment Appointment { get; set; } = null!;

        [Required]
        [Column(TypeName = "decimal(10,2)")]
        public decimal Amount { get; set; }

        [Required]
        [StringLength(10)]
        public string Currency { get; set; } = "INR";

        [Required]
        public PaymentStatus Status { get; set; } = PaymentStatus.Created;

        // --- Razorpay Specific Fields ---

        [Required]
        [StringLength(100)]
        public string RazorpayOrderId { get; set; } = string.Empty; // Generated by backend via Razorpay SDK

        [StringLength(100)]
        public string? RazorpayPaymentId { get; set; } // Returned by checkout widget after success

        [StringLength(255)]
        public string? RazorpaySignature { get; set; } // Used to verify webhook/checkout authenticity

        // --- Audit & Error Fields ---

        public string? FailureReason { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }
    }
}